# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(blank=True, max_length=144)),
                ('follow_through', models.BooleanField(default=False)),
                ('hold_release', models.BooleanField(default=False)),
                ('legs_straight', models.BooleanField(default=False)),
                ('lift_quick', models.BooleanField(default=False)),
            ],
        ),
    ]
