# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court_counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shot',
            old_name='file',
            new_name='filename',
        ),
    ]
