# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_counter', '0004_auto_20171017_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='X',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot',
            name='Y',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=144, unique=True),
        ),
    ]
